Repository kirameki-cafe/Yumi, pull requests merged in 2022-10, with the labels that each got.

#10 Mitigate repo and code to kirameki-cafe
  .github/workflows/docker-image.yml
  README.md
  package.json
  src/discord/Help.ts
Labels: documentation, enhancement

#16 Fix prefix being encoded in the message
  locales/en.json
  locales/jp.json
  locales/th.json
Labels: bug

#17 Updated dependencies and better logging
  package.json
  src/libs/Logger.ts
  yarn.lock
Labels: enhancement, dependencies
